### ISSUE TITLE
有使用server的必要吗？

### ISSUE THREAD

**Issue by micooz** [DIYgod/ZhihuDaily-for-Desktop#2]
不知道这么做的理由是什么？

我觉得没必要再放一个server包在项目里面：
- 一个项目要管两个package对开发者不太友好
- 发布/安装包时会出现问题

**Comment by DIYgod** [comment]
我的想法是将 server 部署到远程服务器上，这样方便更新：多数情况只需要更新服务端而不用用户重新安装客户端。

分成两个 package 是因为我想减小两部分的耦合，server 更像一个相对独立的项目。

然后打包并不会出现问题（在OSX试了下）。

**Comment by micooz** [comment]
@DIYgod 我建议给server再开一个项目。这个项目只做GUI层，另一个就当做web项目好了，这样容易维护和集成。至于web端涉及的跨域请求问题，后面用 [node-http-proxy](https://github.com/nodejitsu/node-http-proxy) 或者用更底层的nginx做个代理就行了。

**Comment by DIYgod** [comment]
的确是我没想周全，还可以用来做 Website 啊

已经将 server 移到 [ZhihuDaily-for-Web](https://github.com/DIYgod/ZhihuDaily-for-Web)
